image: registry.gitlab.isc.org/isc-projects/stork/ci-base:latest

variables:
  POSTGRES_ADDR: postgres:5432
  POSTGRES_DB: storktest
  POSTGRES_USER: storktest
  POSTGRES_PASSWORD: storktest

stages:
  - build

cache:
  key: one-shared-key
  paths:
  - webui/node_modules/
  - tools/

before_script:
  - apt-get update
  - apt-get install -y wget xz-utils rake openjdk-11-jre-headless gcc g++ chromium-browser unzip
  - sysctl -w net.ipv6.conf.all.disable_ipv6=1
  - sysctl -w net.ipv6.conf.default.disable_ipv6=1
  - rake prepare_env

# race_detector:
#   stage: test
#   script:
#     - make race

# memory_sanitizer:
#   stage: test
#   script:
#     - make msan

# code_coverage:
#   stage: test
#   script:
#     - make coverage

# code_coverage_report:
#   stage: test
#   script:
#     - make coverhtml
#   only:
#   - master

lint_go:
  stage: build
  script:
    - rake lint_go

unittest_backend:
  stage: build
  services:
    - name: registry.gitlab.isc.org/isc-projects/stork/ci-postgres:11
      alias: postgres
  script:
    - rake unittest_backend

ci_ui:
  stage: build
  script:
    - rake ci_ui

build_webui:
  stage: build
  script:
    - rake build_ui

danger:
  stage: build
  image: registry.gitlab.isc.org/isc-projects/stork/ci-danger
  before_script:
    - export CI_MERGE_REQUEST_ID=$(git ls-remote -q origin merge-requests\*\head | grep $CI_COMMIT_SHA | sed 's/.*refs\/merge-requests\/\([0-9]*\)\/head/\1/g')
    - export CI_PROJECT_PATH=$CI_PROJECT_ID #some version of gitlab has problems with searching by project path
    - export DANGER_GITLAB_HOST=gitlab.isc.org
    - export DANGER_GITLAB_API_BASE_URL=https://gitlab.isc.org/api/v4
    - sysctl -w net.ipv6.conf.all.disable_ipv6=1
    - sysctl -w net.ipv6.conf.default.disable_ipv6=1
  script:
    - gem install danger-commit_lint
    - danger --fail-on-errors=true --new-comment


tarball:
  stage: build
  script:
    - rake tarball
  artifacts:
    paths:
      - stork-*.tar.gz
    expire_in: 1 week
