version: '3'

services:
  server:
    restart: always
    build:
      context: .
      dockerfile: docker/docker-server.txt
    image: registry.gitlab.isc.org/isc-projects/stork/server:latest
    networks:
      - storknet
    expose:
      - "8080"
    ports:
      - "8088:8080"
    environment:
      STORK_DATABASE_HOST: postgres
      STORK_DATABASE_PORT: 5432
      STORK_DATABASE_USER_NAME: stork
      STORK_DATABASE_PASSWORD: stork123
      STORK_DATABASE_NAME: stork
    depends_on:
      - postgres

  agent-kea:
    restart: always
    build:
      context: .
      dockerfile: docker/docker-agent-kea.txt
    image: registry.gitlab.isc.org/isc-projects/stork/agent-kea:latest
    hostname: agent-kea
    networks:
      storknet:
        ipv4_address: 172.20.0.100
    expose:
      - "8080"

  agent-kea6:
    restart: always
    build:
      context: .
      dockerfile: docker/docker-agent-kea6.txt
    image: registry.gitlab.isc.org/isc-projects/stork/agent-kea6:latest
    hostname: agent-kea6
    networks:
      - storknet
    expose:
      - "8080"

  agent-kea-ha1:
    restart: always
    build:
      context: .
      dockerfile: docker/docker-agent-kea-ha1.txt
    image: registry.gitlab.isc.org/isc-projects/stork/agent-kea-ha1:latest
    hostname: agent-kea-ha1
    networks:
      storknet:
        ipv4_address: 172.20.0.101
    expose:
      - "8001"
    ports:
      - "8881:8080"

  agent-kea-ha2:
    restart: always
    build:
      context: .
      dockerfile: docker/docker-agent-kea-ha2.txt
    image: registry.gitlab.isc.org/isc-projects/stork/agent-kea-ha2:latest
    hostname: agent-kea-ha2
    networks:
      storknet:
        ipv4_address: 172.20.0.102
    expose:
      - "8002"
    ports:
      - "8882:8080"

  agent-bind9:
    restart: always
    build:
      context: .
      dockerfile: docker/docker-agent-bind9.txt
    image: registry.gitlab.isc.org/isc-projects/stork/agent-bind9:latest
    hostname: agent-bind9
    networks:
      - storknet
    expose:
      - "8080"

  webui:
    build:
      context: .
      dockerfile: docker/docker-webui.txt
    image: registry.gitlab.isc.org/isc-projects/stork/webui:latest
    networks:
      - storknet
    ports:
      - "8080:80"
    environment:
      API_HOST: server
      API_PORT: 8080
    depends_on:
      - server

  postgres:
    image: postgres:11
    networks:
      - storknet
    environment:
      POSTGRES_USER: stork
      POSTGRES_PASSWORD: stork123
      POSTGRES_DB: stork


  traffic-dhcp:
    build:
      context: .
      dockerfile: docker/docker-traffic-dhcp.txt
    image: registry.gitlab.isc.org/isc-projects/stork/dhcp-traffic:latest
    hostname: traffic-dhcp
    networks:
      storknet:
        ipv4_address: 172.20.0.200
    environment:
      PERFDHCP_RATE: 1
      PERFDHCP_CLIENTS: 1000

volumes:
  db-data:
  web-data:

networks:
  storknet:
    ipam:
     config:
       - subnet: 172.20.0.0/24
