---
swagger: "2.0"
info:
  description: An API for Stork
  title: Stork API
  version: 0.1.0
consumes:
  - application/json
produces:
  - application/json
schemes:
- http
host: localhost:8765
basePath: /api

securityDefinitions:
  ApiKeyAuth:
    type: apiKey
    in: header
    name: Stork-Auth-Key
paths:
  /user/login:
    get:
      summary: Logs in a user to the system
      parameters:
        - in: query
          name: useremail
          type: string
          description: E-mail of the user logging to the system
        - in: query
          name: userpassword
          type: string
          description: User password to log in to the system
      responses:
        200:
          description: Login successful
        400:
          description: Invalid user email or password supplied

  /version:
    get:
      summary: Get version.
      operationId: getVersion
      security:
        - ApiKeyAuth: []
      tags:
        - General
      responses:
        200:
          description: Version of Stork
          schema:
            $ref: "#/definitions/Version"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/ApiError"

  /machines:
    get:
      summary: Get list of machines.
      description: >-
        It is possible to filter list of machines by several fields. It is also always paged.
        Default page size is 10.
        A list of machines is returned in items field accompanied by total count
        which indicates total available number of records for given filtering
        parameters.
      operationId: getMachines
      tags:
        - Services
      parameters:
        - name: start
          in: query
          description: First record to retrieve.
          type: integer
        - name: limit
          in: query
          description: Number of records to retrieve.
          type: integer
        - name: text
          in: query
          description: Text that is used to match against any field of machines e.g. hostname or address.
          type: string
        - name: service
          in: query
          description: Limit returned list of machines to these which provide given service, possible values 'bind' or 'kea'.
          type: string
      responses:
        200:
          description: List of machines
          schema:
            $ref: "#/definitions/Machines"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/ApiError"
    post:
      summary: Add new machine.
      description: >-
        To create new machine at least one parameter is needed: address.
        There are optional parameters as well.
      operationId: createMachine
      tags:
        - Services
      parameters:
        - name: machine
          in: body
          description: Machine
          schema:
            $ref: '#/definitions/Machine'
      responses:
        200:
          description: Machine information
          schema:
            $ref: "#/definitions/Machine"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/ApiError"

  /machines/{address}/state:
    get:
      summary: Get machine's runtime state.
      operationId: getMachineState
      tags:
        - Services
      parameters:
        - in: path
          name: address
          type: string
          required: true
          description: IP address of machine.
      responses:
        200:
          description: Machine
          schema:
            $ref: "#/definitions/Machine"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/ApiError"



definitions:
  Version:
    type: object
    required:
      - version
      - date
      - type
    properties:
      version:
        type: string
      date:
        type: string
        format: date-time
      type:
        type: string
        enum: [stable, release-candidate, development]

  Machine:
    type: object
    required:
      - address
    properties:
      address:
        type: string
      agentVersion:
        type: string
        readOnly: true
      hostname:
        type: string
        readOnly: true
      cpus:
        type: integer
        readOnly: true
      cpusLoad:
        type: string
        readOnly: true
      memory:
        type: integer
        readOnly: true
      usedMemory:
        type: integer
        readOnly: true
      uptime:
        type: integer
        readOnly: true
      os:
        type: string
        readOnly: true
      platform:
        type: string
        readOnly: true
      platformFamily:
        type: string
        readOnly: true
      platformVersion:
        type: string
        readOnly: true
      kernelVersion:
        type: string
        readOnly: true
      kernelArch:
        type: string
        readOnly: true
      virtualizationSystem:
        type: string
        readOnly: true
      virtualizationRole:
        type: string
        readOnly: true
      hostID:
        type: string
        readOnly: true
      lastVisited:
        type: string
        format: date-time
        readOnly: true
      error:
        type: string
        readOnly: true
  Machines:
    type: object
    properties:
      items:
        type: array
        items:
          $ref: '#/definitions/Machine'
      total:
        type: integer

  ApiError:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
      message:
        type: string

  principal:
    type: string

